### ISSUE TITLE
Use np.matmul in place of @ for backwards support

### ISSUE THREAD

**Issue by suddrey-qut** [jhavl/ropy#1]
This package is fully compatible with Python27 except for the @ operator being used in place of numpy.matmul.

Given that ROS is still largely stuck in Python27 land this is impedes the use of this package over little more than some syntactic sugar.

**Comment by suddrey-qut** [comment]
Pull request submitted.

**Comment by jhavl** [comment]
Merged into ropy-2.7 branch
